const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.NinePatch.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{RiverBackground: 0},
	{SkyBackground: 0},
	{Tween: 0},
	{DialogBox1: 0},
	{Pin: 0},
	{CloseButton: 0},
	{Enable: 0},
	{AddKratongButton: 0},
	{Touch: 0},
	{TextInputWish: 0},
	{TextWish: 0},
	{kratong_num: 0},
	{KratongDemo: 0},
	{NextButton: 0},
	{PreButton: 0},
	{LoyButton: 0},
	{DragDrop: 0},
	{KratongForDrag: 0},
	{Sine: 0},
	{Circle: 0},
	{TextDrag: 0},
	{Logo: 0},
	{KratongBackground: 0},
	{PlayerWishText: 0},
	{KratongPlayer: 0},
	{WishBox: 0},
	{TextInputName: 0},
	{Firework: 0},
	{k_num: 0},
	{text_player_wish: 0}
];

self.InstanceType = {
	RiverBackground: class extends self.ITiledBackgroundInstance {},
	SkyBackground: class extends self.ITiledBackgroundInstance {},
	DialogBox1: class extends self.ITiledBackgroundInstance {},
	CloseButton: class extends self.ISpriteInstance {},
	AddKratongButton: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TextInputWish: class extends self.ITextInputInstance {},
	TextWish: class extends self.ITextInstance {},
	KratongDemo: class extends self.ISpriteInstance {},
	NextButton: class extends self.ISpriteInstance {},
	PreButton: class extends self.ISpriteInstance {},
	LoyButton: class extends self.ISpriteInstance {},
	KratongForDrag: class extends self.ISpriteInstance {},
	Circle: class extends self.ISpriteInstance {},
	TextDrag: class extends self.ITextInstance {},
	Logo: class extends self.ISpriteInstance {},
	KratongBackground: class extends self.ISpriteInstance {},
	PlayerWishText: class extends self.ITextInstance {},
	KratongPlayer: class extends self.ISpriteInstance {},
	WishBox: class extends self.I9PatchInstance {},
	TextInputName: class extends self.ITextInputInstance {},
	Firework: class extends self.ISpriteInstance {}
}